/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.mageddo.togglefirst.examples;

import com.mageddo.togglefirst.FeatureContext;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.context.junit4.SpringRunner;

import static org.junit.Assert.assertEquals;

@SpringBootTest(classes = App.class)
@RunWith(SpringRunner.class)
public class AppIntTest {

	@Autowired
	private CoinsService coinsService;

	@Test
	public void shouldEarnAFreeShop() {
		// arrange

		// act
		final String responseMsg = coinsService.buy("54117", 5.50);

		// assert
		assertEquals("congrats, you earned a free shop", responseMsg);

	}

	@Test
	public void shouldNotHaveEnoughMoney() {
		// arrange
		String userId = "54117";
		FeatureContext.getFeatureManager().deactivate(Parameter.FREE_SHOP);

		// act
		final String responseMsg = coinsService.buy(userId, 5.50);

		// assert
		assertEquals("not enough balance", responseMsg);

	}

}
